### PR TITLE
Fixed breakpoint issue for external packages

### PR DESCRIPTION
**Pull request by levenon**
Fixed breakpoint issue for external packages

### CODE REVIEW

**Comment by cpsauer** [comment]
@levenon, bad news is that #255 (just landed) created some conflicts with this one--but the good news is that I think we might have also solved this problem and a sizable set of additional problems around external workspaces.

Could I ask you to check whether your issue is solved on master (and if not, sorry for the conflicts).

**Comment by thii** [comment]
I think this can be done with an additional remapping in the generated lldbinit?

**Comment by levenon** [comment]
> I think this can be done with an additional remapping in the generated lldbinit?

it doesn't work

**Comment by thii** [comment]
Can you try this?

```diff
-      out.write('settings set target.source-map "%s" "%s"\n' % source_map)
+      out.write('settings set target.source-map "%sexternal/" "%s%s/external/"\n' % (source_map, self.tulsi_workspace))
+      out.write('settings append target.source-map "%s" "%s"\n' % source_map)
```

**Pull request closed without merging**
