### PR TITLE
Quick pass at Swift Modernizing

### PR DESCRIPTION
**Pull request by cpsauer**
Just fixing dead-simple deprecations and warnings I noticed while writing PR #255, broken out for easy reviewing.

No functionality changes and not comprehensive; just a quick tidy.

### CODE REVIEW

**Comment by cpsauer** [comment]
As with #255, tests pass. Failures on last-green-bazel look like a separate rules_apple/Bazel issue.

**Review by segiddins — APPROVED** [review]

**Comment by cpsauer** [comment]
Thanks for the quick review! 

Could we land her, cap'n? :)

**Comment by cpsauer** [comment]
@segiddins, any chance I could get you help merging this PR--and maybe the others?

**Comment by segiddins** [comment]
I can merge once the build goes green

**Comment by cpsauer** [comment]
Just administratively, right, not concerned about code correctness, given all PRs are failing this way?
I assume the tests won't rerun, so where do we go from there?

**Comment by cpsauer** [comment]
Saw Keith had fixed the tests a few days ago, so I merged that in--and everything's now green :)

@segiddins, any chance I could get your help merging this one, and maybe also some of the more serious fixes (#257, #255)

**Review by thii — APPROVED** [review]

**Comment by cpsauer** [comment]
Whoa, that was fast, @thii

(Rerunning tests on the others the same way)

**Pull request merged**
