### PR TITLE
Pull in upstream fixes

### PR DESCRIPTION
**Pull request by keith**
This is a bulk merge of multiple upstream commits, best to review commit by commit

### CODE REVIEW

**Comment by segiddins** [comment]
Bunch of aspect test failures: https://storage.googleapis.com/bazel-untrusted-buildkite-artifacts/c0e438cb-098f-46ef-8228-bb71e42c9739/src/TulsiGeneratorIntegrationTests/AspectTests/attempt_1.log

**Comment by ivanhernandez13** [comment]
The aspect tests were updated and depend on a [new feature](447d99bb2e5e1165fe5347cc02c3163bcb688188) of rules_apple which I did not realize had not been pushed upstream yet. Updating the rules apple checkout fixes the aspect tests locally on my machine. Can push out another change to update the rules to the proper commit.

**Comment by ivanhernandez13** [comment]
Pushed https://github.com/bazelbuild/tulsi/commit/559c696439e11013b6325f66d109d7dafa9627c9 for rules_apple update.

**Review by BalestraPatrick — APPROVED** [review]
Thanks for this! LGTM.

**Pull request merged**
