### PR TITLE
Migrate to new build system introduced in Xcode 10, deprecated in Xcode 13

### PR DESCRIPTION
**Pull request by jgavris**
- Very simple first pass, I'm not sure if there any projects that are blocked from migrating to the new build system (it's been a few years since it was introduced). If necessary I could add an opt-in command line argument for this.

### CODE REVIEW

**Comment by cpsauer** [comment]
@thii, @DavidGoldman, any chance I could bump the request for a review of this? 
[Likely super fast review and removes a broad annoyance, including internally, pending context about legacy-build-system use, perhaps internally at Google.]

**Comment by DavidGoldman** [comment]
We'll need to do some more testing to make this sure works as expected, especially w.r.t codesigning and running on device; we should also put this behind a project setting - it's possible we may only support the new build system on specific versions of Xcode (e.g. 13+)

**Comment by wendyliga** [comment]
agree with @DavidGoldman, on our own maintained tulsi, we add option to set it as legacy or not
https://github.com/wendyliga/tulsi-plus-plus/pull/29/commits/b2c8e31ee80eb1d1e4f78ac0419af31e3d80232a

**Comment by cpsauer** [comment]
Got it.

Should have linked before, but for any other readers, the context about this being upgraded to an error in Xcode 13--and a workaround in the meantime--are in https://github.com/bazelbuild/tulsi/pull/269#issuecomment-939288426

**Comment by jgavris** [comment]
@DavidGoldman would you accept @wendyliga's PR to add an option to enable the new build system? Should I just update this one to make it 'opt-in'?

**Comment by DavidGoldman** [comment]
Yeah, a `UseLegacyBuildSystem` flag seems reasonable although it should default to true for now. I can also send that out, probably is easier for me to to just do it.

**Comment by jgavris** [comment]
@DavidGoldman thanks! Our projects require it.

**Comment by DavidGoldman** [comment]
Just added the flag in upstream for @thii or @keith to merge into main. Have done some testing today with the new build system, here's what I've noticed:

- We need to set `CODE_SIGNING_ALLOWED` to `NO` otherwise we'll get an error while building related to a signing identity being required (confirmed for devices, might also happen for simulator)
- Newer versions of Xcode (tested with 13.1 at the moment) copy the testing frameworks before running the shell script, so we need to be sure that we don't delete them when we copy over the .app bundle otherwise the tests will fail to run since the testing frameworks/dylibs are deleted. I don't think this will work properly on older versions of Xcode (likely 11/12) since the older versions will copy over the frameworks after our scripts run, but I need to confirm.
- With that, testing seems to work OK on device, but I see distracting errors like:

```
Unable to open dependencies file (/Users/davg/Library/Developer/Xcode/DerivedData/Widevine-axduonfojkmklofdcamyatcplwej/Build/Intermediates.noindex/Widevine.build/__TulsiTestRunner_Debug-iphoneos/FunctionalTest.build/Objects-normal/arm64/Tests.d)
Command CompileSwiftSources emitted errors but did not return a nonzero exit code to indicate failure
```

which ideally we'll be able to disable or workaround to avoid user confusion.

**Pull request closed without merging**
