### PR TITLE
Add arm64 (Apple Silicon) to valid CPUs for macOS

### LINKED ISSUE #206: Apple Silicon macos_arm64 not included in compilation targets
When building macOS on Apple Silicon:

```
Queuing Tulsi build...
:: error: Unknown active compilation target of "macos_arm64". Please report a Tulsi bug.
```

Seems to be a simple omission here:
https://github.com/bazelbuild/tulsi/blob/master/src/TulsiGenerator/DeploymentTarget.swift#L117

### PR DESCRIPTION
**Pull request by erikkerber**
Resolves #206 

I'm new to Tulsi and am unsure if there is a test suite covering `validCPUs`, but do point them out if I'm just missing them!

### CODE REVIEW

**Comment by erikkerber** [comment]
@googlebot I fixed it.

**Comment by erikkerber** [comment]
@googlebot I fixed it.

**Comment by DavidGoldman** [comment]
I think the existing code in BazelBuildSettingsFeatures.swift should handle the new case automatically. I think it might also make sense to add arm64e to that list though? I think that's used for kernel extensions?

**Comment by erikkerber** [comment]
> I think the existing code in BazelBuildSettingsFeatures.swift should handle the new case automatically.

Yes! I was able to build and run a macOS app with the change

> I think it might also make sense to add arm64e to that list though?

I'll be honest I haven't done enough reading on arm64e yet, but I believe that yes it should be included. I'll add it.

**Review by DavidGoldman — COMMENTED** [review]
LGTM, will let @keith merge into master, I will merge into our upstream branch tomorrow

**Comment by keith** [comment]
thanks!

**Pull request merged**
