### PR TITLE
generator/pbtargetgenerator: modify header path defined in copts from…

### PR DESCRIPTION
**Pull request by xinzhengzhang**
generator/pbtargetgenerator: modify header path defined in copts from cflags to include header

### CODE REVIEW

**Comment by xinzhengzhang** [comment]
I signed it!

**Comment by DavidGoldman** [comment]
Hi! Thanks for the PR.

A couple questions to help me understand this better:
* Are you seeing any difference in behavior between keeping the `-I` and `-iquote` flags in `OTHER_CFLAGS` vs. `HEADER_SEARCH_PATHS`?
* How is `HEADER_SEARCH_PATHS` used by Xcode? According to [this reference](https://pewpewthespells.com/blog/buildsettings.html#header_search_paths), Xcode simply treats them as `-I <dir>` flags like we currently support - this might end up breaking any `-iquote` flags that you rely on. Is this more of a flag ordering issue?

**Comment by DavidGoldman** [comment]
Friendly ping

**Comment by xinzhengzhang** [comment]
Friendly pang

**Comment by xinzhengzhang** [comment]
@DavidGoldman ping - -

**Comment by DavidGoldman** [comment]
Do you mind rebasing this PR against HEAD so I can test this internally?

**Comment by xinzhengzhang** [comment]
Done

**Comment by DavidGoldman** [comment]
Hmm, can you try re-uploading? Think it might be fixed

**Comment by xinzhengzhang** [comment]
Rebased but there is still something wrong with environment  like 
`IOError: [Errno 1] Operation not permitted: '/Users/travis/.lldbinit`
 cause bazel test fail

**Comment by keith** [comment]
Feel free to open a new PR if this is still an issue

**Pull request closed without merging**
