### PR TITLE
Fix issues for Xcode 11.2.1

### PR DESCRIPTION
**Pull request by jerrymarino**
Xcode 11.2.1 Xcode uses the wrong fix # version number ( set to 1120 )

Change-Id: Id3b5ec6a43b6579f9a0bcee8663c5ddf29a16e4b

### CODE REVIEW

**Comment by jerrymarino** [comment]
Good moring Tulsi team! We hit this issue in 11.2.1 and are using `xcodebuild` directly to get the Xcode version in XCHammer . I originally considered reading this value directly from Xcode's plist, but `xcodebuild` seems to do that for us without parsing the plist.

**Comment by DavidGoldman** [comment]
Can you include a dump of all of the env vars present in Xcode 11.2.1's shell script phase execution? Is the `XCODE_PRODUCT_BUILD_VERSION` correct? It might be best to identify Xcode 11.2.0/11.2.1 and special case it...

**Comment by DavidGoldman** [comment]
Are you sure this isn't a corrupted installation on your end? I see `export XCODE_VERSION_ACTUAL=1121` locally.

**Comment by jerrymarino** [comment]
I agree, if this is a bug and there's a way to patch this then let's hard code. A handful of devs hit this error when downloaded 11.2.1 when it first came out ( near `11/5` ). If it's fixed in the app store, feel free to close out!

**Comment by DavidGoldman** [comment]
Friendly ping, have you looked further into this?

**Comment by DavidGoldman** [comment]
Closing due to inactivity, feel free to re-open/ping if you're still seeing this.

**Pull request closed without merging**
