### PR TITLE
Added announcement banner class for announcing things to Tulsi users

### PR DESCRIPTION
**Pull request by thii**
This is currently unused.

PiperOrigin-RevId: 429136722
(cherry picked from commit c8927202d75c2811de97b7eaa7238bdf3d0c7d3a)

### CODE REVIEW

**Review by keith — APPROVED** [review]

**Comment by thii** [comment]
@keith Can you merge? The commit author noreply@google.com doesn't pass the required CLA check.

**Comment by brentleyjones** [comment]
That isn't a blocking merge, there are other CI failures.

**Comment by thii** [comment]
It's a required check AFAICT. I don't have access to the admin settings but it has a "Required" label.
Screen Shot 2022-07-25 at 22 08 03

**Comment by brentleyjones** [comment]
Okay. Either way, these are failing:
CleanShot 2022-07-25 at 08 18 38@2x

**Comment by thii** [comment]
We've been using GitHub Actions as a temporary replacement for BazelCI here because of https://github.com/bazelbuild/continuous-integration/issues/1273.

**Comment by keith** [comment]
I removed that as a requirement, which we've already done on the other repos, we just have to be careful to verify it for cases besides this one. you should be able to merge now

**Comment by thii** [comment]
Thanks!

**Pull request merged**
