### PR TITLE
Support XCFramework

### PR DESCRIPTION
**Pull request by wendyliga**
add function to collect XCFramework on bazel aspect, to support [native xcframework rules](https://github.com/bazelbuild/rules_apple/blob/master/doc/rules-apple.md#apple_dynamic_xcframework_import)

|Before|After|
|----|----|
|Screen Shot 2022-04-21 at 15 28 10|Screen Shot 2022-04-21 at 15 19 42|

### CODE REVIEW

**Comment by wendyliga** [comment]
any update regarding this @keith?

**Review by keith — APPROVED** [review]

**Comment by keith** [comment]
Thanks!

**Comment by thii** [comment]
@wendyliga I think this adds `-F` to the parent directory of the `.xcframework` to the Xcode build settings which seems off?

**Comment by wendyliga** [comment]
@thii you are right, on `xcodebuild`, they copy the framework based on the arch to `derivedData`, and refer to that path as `-F`.

**Comment by thii** [comment]
Fixing here https://github.com/bazelbuild/tulsi/pull/351

**Comment by wendyliga** [comment]
> Fixing here #351

works like a charm, thanks @thii

**Pull request merged**
