### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by dslomov**
Adding all GitHub repo admins as global CODEOWNERS

### CODE REVIEW

**Comment by dierksen** [comment]
Current maintainers are me (dierksen), DavidGoldman, reinhillmann, and ivanhernandez13.

**Comment by dierksen** [comment]
> Should all these people be repository admins as well?
The repository admins are probably fine as is.

I'll get this merged in after I take a look at the buildkite/travis issues.

**Comment by dierksen** [comment]
I removed abaire, as he hasn't be involved with Tulsi for a while now; the rest should probably stay as they're (at least) indirectly responsible for managing things still.

**Comment by dslomov** [comment]
> I removed abaire, as he hasn't been involved with Tulsi for a while now; the rest should probably stay as they're (at least) indirectly responsible for managing things still.

Ok, sgtm. Thank you!

**Comment by dslomov** [comment]
@dierksen how to go about merging this? (CI failures seem unrelated)

**Pull request closed without merging**
