### PR TITLE
Fix broken external BuildLabel filename parsing

### PR DESCRIPTION
**Pull request by cpsauer**
External BuildLabels were keeping their // halfway through their path, leading to projects xcode would refuse to load.

As an example: @google_toolbox_for_mac//Foundation:BUILD was going to external//Foundation/BUILD, not external/Foundation/BUILD.
This lead the pbjproj to assign the file the path //Foundation/BUILD, which Xcode refuses to load, along with groups named '/' and the omission of other associated source files.

[Noticed while writing #255, separated for ease of review.]

### CODE REVIEW

**Comment by cpsauer** [comment]
As with #255, tests pass. Failures on last-green-bazel look like a separate rules_apple/Bazel issue.

**Comment by cpsauer** [comment]
@thii or @segiddins, could I get a review on this? Pretty sure it'll be a quick, clear bug fix.

**Review by thii — APPROVED** [review]
LGTM

**Comment by cpsauer** [comment]
@thii, thanks for accepting! I really appreciate your getting it in.

Could I ask you to also review #255, for the hat trick? 

I'm asking you in particular both because you've been so helpful and because we'd discussed the issue it solves in the past. It's definitely a bigger contribution than this one, but it'd be really great to get in and I promise it's a high quality improvement.

**Comment by cpsauer** [comment]
@DavidGoldman, I got reminded of this again while taking to some Googlers. Any chance I can help you get some of these other (IMO quite valuable) fixes into upstream?

**Pull request merged**
